Fix issues with mimeType not matching on 0
When generating a site, I keep encountering an issue where mimeType is not matching on 0

var type = mimeType.match(/^\s*([^;\s]*)(?:;|\s|$)/)[1].toLowerCase();
                      ^
TypeError: Object false has no method 'match'

This is because the 'accept_types' arg of 'getExtension' is an empty array